name: Build Debug APK
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'

      - name: Set Up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'

      - name: Install Dependencies
        run: npm install

      - name: Grant Execution Permission to Gradle
        run: chmod +x android/gradlew

      - name: Build Debug APK
        run: |
          cd android
          ./gradlew assembleDebug --stacktrace --info

      - name: Verify APK Exists
        run: |
          echo "Checking APK..."
          ls -lah android/app/build/outputs/apk/debug/app-debug.apk

      - name: Upload APK as Artifact
        uses: actions/upload-artifact@v4
        with:
          name: debug-app
          path: android/app/build/outputs/apk/debug/app-debug.apk
